// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    FragmentForm: typeof import('./../src/components/fragments/FragmentForm.vue')['default']
    FragmentTable: typeof import('./../src/components/fragments/FragmentTable.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualForm: typeof import('./../src/components/virtual-ui/VirtualForm.vue')['default']
    VirtualTable: typeof import('./../src/components/virtual-ui/VirtualTable.vue')['default']
  }
}
